### ISSUE TITLE
Run out of memory in colab

### ISSUE THREAD

**Issue by wwwccttoo** [Nicholaswogan/NumbaQuadpack#1]
I define functions like this: 
```
from NumbaQuadpack import quadpack_sig, dqags
import numpy as np
import numba as nb

@nb.cfunc(quadpack_sig)
def Cfunc_value2int(tau, data_):
    data = nb.carray(data_, (2,))
    internal_data = data[0] + (data[1] - data[0]) / 0.13 * tau
    if internal_data <= 39:
        return 0
    elif internal_data >= 43:
        return np.power(0.5, 43 - internal_data)
    else:
        return np.power(0.25, 43 - internal_data)


K_valuecptr = Cfunc_value2int.address
the_plane_shape = 51


@nb.njit()
def Cfunc_surf_acc_calculate(tau, data):
    mask = np.zeros((the_plane_shape, the_plane_shape))
    for i in range(the_plane_shape):
        for j in range(the_plane_shape):
            mask[i,j], _, _ = dqags(K_valuecptr, 0, tau, data=data[i, j, :])
    return mask
```
and call the Cfunc_surf_acc_calculate within a for loop. it finally eats all the 25 GB RAM in google colab as more for loops were conducted and gives:
`tcmalloc: large alloc 3955040256 bytes == 0x55a98831e000 @  0x7f3688f1b1e7 0x7f3592d5a46e 0x7f3592daac7b 0x7f3592daad18 0x7f3592e52010 0x7f3592e5273c 0x7f3592e5285d 0x55a22b9f6749 0x7f3592d97ef7 0x55a22b9f4437 0x55a22b9f4240 0x55a22ba67973 0x55a22ba629ee 0x55a22b9f5bda 0x55a22ba67d00 0x55a22ba629ee 0x55a22b9f5bda 0x55a22ba63c0d 0x55a22b9f5afa 0x55a22ba63c0d 0x55a22ba629ee 0x55a22b9f5bda 0x55a22ba64737 0x55a22b9f5afa 0x55a22ba63c0d 0x55a22b9f5afa 0x55a22ba63915 0x55a22ba629ee 0x55a22ba626f3 0x55a22bb2c4c2 0x55a22bb2c83d
`

**Comment by Nicholaswogan** [comment]
This is likely a memory leak issue with NumbaQuadpack. I'll take a look!

**Comment by Nicholaswogan** [comment]
I don't see how memory could be leaking here. Can you send me more of the code that reproduces the high ram usage?

**Comment by wwwccttoo** [comment]
Ok! the code calls the Cfunc_surf_acc_calculate is inside a class, but it basically does:
```
for _ in range(10):
            A = np.random.uniform(39, 43, (51,51))
            B = np.random.uniform(39, 43, (51,51))
            # used the outside function
            self.CEM_surface += Cfunc_surf_acc_calculate(0.13, np.concatenate((A[None].reshape(51, 51, 1), B[None].reshape(51, 51, 1)), axis=2))
```
and this for loop will be excuted larger than 100000 times (10*100000 calculations)

**Comment by wwwccttoo** [comment]
Many thanks for helping me! I have located the issue, which is from the package I am using. This package probably appends the new data in a bad manner consuming a lot of memory, which causes the crash.
